### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7. 

### ISSUE THREAD

**Issue by TralahM** [Alacritous/DDS_directory_structure#1]
```Traceback (most recent call last):
  File "ddcgo.py", line 69, in <module>
    for row in csv_reader:
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 7615: invalid continuation byte```

**Comment by Alacritous** [comment]
It didn't give any error when I ran it when I wrote it. That was Python 3.5 or .6 I think I don't remember.  But cool, thanks for the fix.
